## 파이썬 브로드캐스팅 예시

In [1]:
import numpy as np

In [15]:
A = np.array([[56, 0, 4.4, 68], [1.2, 104, 52, 8], [1.8, 135, 99, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [16]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [17]:
percentage = 100* A/ cal.reshape(1,4)

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## 브로드캐스팅 오류 잡기

In [18]:
a= np.random.randn(5)

print(a)

[ 0.53885859 -2.34572409  1.1494648   0.32714599  0.57922105]


In [19]:
a.shape

(5,)

* 랭크가 1인 배열, 행벡터도아니고 열벡터도 아니다. --> 직관적이지 않다.

In [23]:
a.T.shape

(5,)

- 랭크가 1인 배열끼리 곱하면 행렬이 되지않는다!!!

In [24]:
np.dot(a,a.T)

7.556580962468979

- 따라서 (n,1) , (1,n) 벡터모양으로 만들어 준 후 계산해야한다.

In [30]:
a = np.random.randn(5,1)
print(a)

[[-0.45406367]
 [ 1.06556918]
 [-0.7335403 ]
 [ 0.09381137]
 [ 0.34837861]]


In [31]:
print(np.dot(a, a.T))

[[ 0.20617382 -0.48383625  0.333074   -0.04259634 -0.15818607]
 [-0.48383625  1.13543768 -0.78163794  0.09996251  0.37122151]
 [ 0.333074   -0.78163794  0.53808137 -0.06881442 -0.25554975]
 [-0.04259634  0.09996251 -0.06881442  0.00880057  0.03268188]
 [-0.15818607  0.37122151 -0.25554975  0.03268188  0.12136766]]


In [34]:
assert(a.shape == (5,1))

In [41]:
np.sum(a, axis=1, keepdims=True)

array([[ 0.58294326],
       [-0.6236852 ],
       [ 0.74227357],
       [-0.55850022]])